name         'stdmod-kibana'
version '0.0.2'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-kibana'
summary      'Puppet module for kibana'
description  'This module installs and manages kibana. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
