name         'example42-kibana'
version '3.0.3'
author       'Example42'
license      'Apache2'
project_page 'https://github.com/example42'
source       'https://github.com/example42/puppet-kibana'
summary      'Puppet module for kibana'
description  'This module installs and manages kibana. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
